### ISSUE TITLE
IPMI PSU queries always show Critical

### ISSUE THREAD

**Issue by DebianGuru** [thomas-krenn/check_ipmi_sensor_v3#33] opened 2020-04-07 19:03 UTC
Thanks for your excellent work.  I've set this up for Nagios core but I seem to get a Critical error about the power supplies.   Here's what I get when I run it with the -vvv flags for debugging:

------------- debug output for sel (-vvv is set): ------------
  /usr/sbin/ipmi-sel was executed with the following parameters:
    /usr/sbin/ipmi-sel -h 172.17.8.91 --config-file /etc/ipmi-config/ipmi.cfg --driver-type=LAN_2_0 --output-event-state --interpret-oem-data --entity-sensor-names
  output of FreeIPMI:
ID  | Date        | Time     | Name                                           | Type                        | State    | Event
1   | Feb-15-2020 | 09:03:20 | System Management Software SEL Fullness        | Event Logging Disabled      | Nominal  | Log Area Reset/Cleared
2   | Mar-23-2020 | 11:52:18 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
3   | Mar-23-2020 | 11:52:28 | Front Panel Board Front Panel                  | Entity Presence             | Nominal  | Entity Present
4   | Mar-23-2020 | 11:52:29 | Cable/Interconnect 2 Front Video               | Cable/Interconnect          | Nominal  | Cable/Interconnect is connected
5   | Mar-23-2020 | 11:52:38 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
6   | Mar-23-2020 | 11:52:44 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
7   | Mar-23-2020 | 11:52:57 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
8   | Mar-23-2020 | 11:53:02 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
9   | Mar-23-2020 | 11:54:23 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; User-initiated system setup
10  | Mar-23-2020 | 15:01:47 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
11  | Mar-23-2020 | 15:01:52 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
12  | Mar-23-2020 | 15:01:56 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
13  | Mar-23-2020 | 15:02:04 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
14  | Mar-23-2020 | 15:11:14 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
15  | Mar-23-2020 | 15:36:01 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
16  | Mar-23-2020 | 15:37:06 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
17  | Mar-24-2020 | 12:29:55 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
18  | Mar-24-2020 | 12:31:07 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
19  | Mar-24-2020 | 12:56:48 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
20  | Mar-24-2020 | 12:56:53 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
21  | Mar-24-2020 | 12:56:58 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
22  | Mar-24-2020 | 12:57:05 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
23  | Mar-24-2020 | 12:58:21 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
24  | Mar-24-2020 | 13:00:57 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
25  | Mar-24-2020 | 13:01:08 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
26  | Mar-24-2020 | 13:01:12 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
27  | Mar-24-2020 | 13:01:20 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
28  | Mar-24-2020 | 13:03:35 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
29  | Mar-24-2020 | 13:24:38 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
30  | Mar-24-2020 | 13:24:43 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
31  | Mar-24-2020 | 13:24:47 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
32  | Mar-24-2020 | 13:24:55 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
33  | Mar-24-2020 | 13:25:59 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; User-initiated system setup
34  | Mar-24-2020 | 13:27:53 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
35  | Mar-24-2020 | 13:29:18 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
36  | Mar-24-2020 | 13:45:04 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
37  | Mar-24-2020 | 13:46:14 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
38  | Mar-24-2020 | 13:50:34 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
39  | Mar-24-2020 | 13:52:49 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
40  | Mar-24-2020 | 14:03:18 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
41  | Mar-24-2020 | 14:04:30 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
42  | Mar-24-2020 | 14:53:35 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
43  | Mar-24-2020 | 14:54:46 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
44  | Mar-25-2020 | 13:35:44 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
45  | Mar-25-2020 | 13:36:53 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
46  | Mar-25-2020 | 13:36:59 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
47  | Mar-25-2020 | 13:37:02 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
48  | Mar-25-2020 | 13:37:12 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
49  | Mar-25-2020 | 10:43:10 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
50  | Mar-26-2020 | 14:26:48 | Power Supply 2                                 | Power Supply                | Critical | Power Supply input lost (AC/DC)
51  | Mar-26-2020 | 14:26:49 | Power Unit 1 Power Resource                    | Power Unit                  | Critical | Non-redundant:Sufficient Resources from Redundant
52  | Mar-26-2020 | 14:28:38 | Power Supply 2                                 | Power Supply                | Warning  | Power Supply input lost (AC/DC)
53  | Mar-26-2020 | 14:28:39 | Power Unit 1 Power Resource                    | Power Unit                  | Warning  | Non-redundant:Sufficient Resources from Redundant
54  | Mar-26-2020 | 14:30:34 | Power Unit 1 Power Resource                    | Power Unit                  | Critical | Non-redundant:Sufficient Resources from Redundant
55  | Mar-26-2020 | 14:30:36 | Power Supply 1                                 | Power Supply                | Critical | Power Supply input lost (AC/DC)
56  | Mar-26-2020 | 14:32:26 | Power Supply 1                                 | Power Supply                | Warning  | Power Supply input lost (AC/DC)
57  | Mar-26-2020 | 14:32:29 | Power Unit 1 Power Resource                    | Power Unit                  | Warning  | Non-redundant:Sufficient Resources from Redundant
58  | Mar-26-2020 | 18:11:47 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
59  | Mar-26-2020 | 18:12:44 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
60  | Mar-26-2020 | 18:12:49 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
61  | Mar-26-2020 | 18:12:56 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
62  | Mar-26-2020 | 18:15:31 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
63  | Mar-26-2020 | 18:18:04 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
64  | Mar-26-2020 | 18:18:06 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
65  | Mar-26-2020 | 18:18:11 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
66  | Mar-26-2020 | 18:18:24 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
67  | Mar-26-2020 | 18:20:13 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
68  | Mar-26-2020 | 18:49:18 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
69  | Mar-26-2020 | 18:50:31 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
70  | Apr-07-2020 | 14:58:22 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
71  | Apr-07-2020 | 15:03:10 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
72  | Apr-07-2020 | 15:03:18 | Power Unit 1 Host Power                        | Power Unit                  | Nominal  | Power Off/Power Down
73  | Apr-07-2020 | 15:03:22 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
74  | Apr-07-2020 | 15:03:30 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
75  | Apr-07-2020 | 15:04:44 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
76  | Apr-07-2020 | 15:10:57 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
77  | Apr-07-2020 | 15:12:10 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
78  | Apr-07-2020 | 15:16:32 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Unspecified
79  | Apr-07-2020 | 15:17:45 | System Firmware Progress                       | System Firmware Progress    | Nominal  | System Firmware Progress ; Starting operating system boot process, e.g. calling Unsigned Int 19h
------------- debug output for sensors (-vvv is set): ------------
  script was executed with the following parameters:
    ./check_ipmi_sensor -f /etc/ipmi-config/ipmi.cfg -H 172.17.8.91 -vvv --nothresholds -T Power_Supply
  check_ipmi_sensor version:
    3.9
  FreeIPMI version:
    ipmi-sensors - 1.6.3
  FreeIPMI was executed with the following parameters:
    /usr/sbin/ipmi-sensors -h 172.17.8.91 --config-file /etc/ipmi-config/ipmi.cfg -g Power_Supply --quiet-cache --sdr-cache-recreate --interpret-oem-data --output-sensor-state --ignore-not-available-sensors --driver-type=LAN_2_0
  FreeIPMI return code: 0
  output of FreeIPMI:
ID | Name             | Type         | State    | Reading    | Units | Event
14 | Power Supply 1   | Power Supply | Nominal  | N/A        | N/A   | 'Presence detected'
15 | PSU1 Failure     | Power Supply | Nominal  | N/A        | N/A   | 'transition to OK'
16 | PSU1 PF Failure  | Power Supply | Nominal  | N/A        | N/A   | 'transition to OK'
17 | PSU1 IN Failure  | Power Supply | Nominal  | N/A        | N/A   | 'transition to OK'
20 | Power Supply 2   | Power Supply | Nominal  | N/A        | N/A   | 'Presence detected'
21 | PSU2 Failure     | Power Supply | Nominal  | N/A        | N/A   | 'transition to OK'
22 | PSU2 PF Failure  | Power Supply | Nominal  | N/A        | N/A   | 'transition to OK'
23 | PSU2 IN Failure  | Power Supply | Nominal  | N/A        | N/A   | 'transition to OK'
72 | Ext Enclosure PS | Power Supply | Nominal  | N/A        | N/A   | 'OK'

--------------------- end of debug output ---------------------
Sensor Type(s) Power_Supply Status: Critical [Power Supply 2 = Critical (Power Supply), Power Unit 1 Power Resource = Critical (Power Unit), Power Supply 2 = Warning (Power Supply), Power Unit 1 Power Resource = Warning (Power Unit), Power Unit 1 Power Resource = Critical (Power Unit), Power Supply 1 = Critical (Power Supply), Power Supply 1 = Warning (Power Supply), Power Unit 1 Power Resource = Warning (Power Unit)]
Power Supply 1 = 'Presence detected' (Status: Nominal)
PSU1 Failure = 'transition to OK' (Status: Nominal)
PSU1 PF Failure = 'transition to OK' (Status: Nominal)
PSU1 IN Failure = 'transition to OK' (Status: Nominal)
Power Supply 2 = 'Presence detected' (Status: Nominal)
PSU2 Failure = 'transition to OK' (Status: Nominal)
PSU2 PF Failure = 'transition to OK' (Status: Nominal)
PSU2 IN Failure = 'transition to OK' (Status: Nominal)
Ext Enclosure PS = 'OK' (Status: Nominal)

If I understand this properly, it is showing both power supplies and the output from FreeIPMI shows the power supplies in a "Nominal" state.  But script is returns:
 "Sensor Type(s) Power_Supply Status: Critical [Power Supply 2 = Critical (Power Supply), Power Unit 1 Power Resource = Critical (Power Unit), Power Supply 2 = Warning (Power Supply), Power Unit 1 Power Resource = Warning (Power Unit), Power Unit 1 Power Resource = Critical (Power Unit), Power Supply 1 = Critical (Power Supply), Power Supply 1 = Warning (Power Supply), Power Unit 1 Power Resource = Warning (Power Unit)]"

How are these in a Critical state if they returned "Nominal" result.  Maybe I don't understand or the script is looking for some other value to be returned?  Thanks for the help.

**Comment by veitw** [comment] 2020-04-07 19:24
Hi, 

this is caused by the power supply events in your system event log. This ensures that not only completely defective PSUs are detected, but also flaky ones, temporary problems or power circuit/UPS failures. Also other problems are detected this way that would not show up in interval checks, e.g. ECC corrections that might indicate upcoming RAM failures if recurring, or chassis events indicating physical attacks. 

You will want to review all events logged, maybe save one or more events for later (PSU failures, ECC errors,... as they indicate problems when recurring) and clear the log afterwards. Then the check will complete OK. 
You can use the ipmi-sel command for this.

Best regards, 
// Veit

**Comment by DebianGuru** [comment] 2020-04-07 19:40
Thanks a million! It's a brand new server.  It was crying because at some
point during setup one PSU was not plugged in.


Jay Fluharty
Network Analyst
Wheeling-Nippon Steel Inc.
PO Box 635
Follansbee, WV 26037
jayf@wheeling-nipponsteel.com
1-304-527-4819

**Comment by veitw** [comment] 2020-04-07 20:10
Glad it helped. :) 

Please close the issue if the problem is solved for you, so the guys at TK can focus on something else. I am not affiliated with TK and thus cannot do this.

**Comment by gschoenberger** [comment] 2020-04-08 05:37
THX @veitw for clarification!
If you want to clear the IPMI System Event Log you can use `ipmi-sel --clear`.
On a healthy server normally no additional entries should appear in the event log.
All the best, Georg

**Closed by gschoenberger** 2020-04-08 05:37 UTC
